language: python
sudo: required
services:
  - docker

before_install:
  - docker build -t journald-2-cloudwatch -f Dockerfile .
install:
  - docker build -t journald-2-cloudwatch-test -f Dockerfile.test .
script:
  docker run --rm -v `pwd`:/coverage journald-2-cloudwatch-test

after_success:
  coveralls
