sudo: required
services:
  - docker

before_install:
  - docker build -t journald-2-cloudwatch -f Dockerfile .
install:
  - docker build -t journald-2-cloudwatch-test -f Dockerfile.test .
before_script:
  - 'env | grep TRAVIS > env'
script:
  docker run --env-file=env --rm -v `pwd`:`pwd` -w `pwd` journald-2-cloudwatch-test
after_success:
  coveralls
